### ISSUE TITLE
Module 5 Group Project Kanban board

### ISSUE THREAD

**Issue by Donmark2k** [Donmark2k/food_recipe#26]
This is the link to our project kanban board
https://github.com/users/Donmark2k/projects/5/views/1?layout=board
We are 3 members in this team @MosDevx , @quavo19  and @Donmark2k

**Comment by OyePriscilla** [comment]
Hi @Donmark2k, @MosDevx and @quavo19 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

![so-close](https://user-images.githubusercontent.com/103386183/196423863-0f522555-1b03-455e-a452-b822cdcfc398.gif)

## Highlights
Set up kanban board ✔️ 
Task assigned fairly to all the group members ✔️ 

## Required Changes ♻️

- [ ] Kindly ensure that the **In Review** column is added to your project, it's one of the standardized way of using GitHub project feature. 👍

<img width="799" alt="Untitled" src="https://github.com/Donmark2k/food_recipe/assets/103386183/8a8040a3-475f-4af8-87a2-e0a3e27ab2fb">

- [ ] All your tasks has no description added to them, kindly implement this to make your project to be more descriptive. 👍 
<img width="540" alt="Untitled" src="https://github.com/Donmark2k/food_recipe/assets/103386183/0a2e56cb-44f5-42ab-8a72-6c05c76aa44f">

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Donmark2k** [comment]
@OyePriscilla , we have carried out the required changes. Thanks for the feedback

**Comment by mckent05** [comment]
Hi team, 

# STATUS: APPROVED ✔️ ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to start your capstone, good luck 🎉 
Congratulations and well done! 🎉 
![approved](https://user-images.githubusercontent.com/73607512/207264357-1b05ce6a-95f2-4d31-9c26-888c6ddfa124.gif)


## Highlights
- All tasks are fairly assigned ✔️ ✔️ 
- Kanban board has been properly setup 👍 👍 
## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by Donmark2k** [comment]
@mckento05, thank you
